server:
  port: 10086
spring:
  application:
    name: leyou-registry
eureka:
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:10086/eureka
  server:
    enable-self-preservation: false   #关闭自我保护模式
    eviction-interval-timer-in-ms:  10000   #清理无效链接间隔

